### ISSUE TITLE
Create subtheme instructions/template

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#127]
There is [some info about how to sub-theme our kickstart theme](https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/8.x-1.x/themes/custom/apigee_kickstart/README.md), but would be good to add more detail and a template so that persons new to Drupal 8 theming can easily understand how to make modifications to the look and feel of Kickstart.

**Comment by jacine** [comment]
We could potentially use Tour module to enhance certain aspects, related to the theme.  For example, on the Block Layout page would could use the Tour module to describe each theme region and its purpose.

**Comment by shadcn** [comment]
I'm doing some work in the Radix base theme to make this easier. I'll comment here when I have some updates.

**Comment by jacine** [comment]
Just a quick update here.  Still working on this, but wanted to provide a quick update here, and note some of the issues it has spawned.

## Starterkit for creating a subtheme

Support for Drush 9 subtheme generation was recently added to Radix.  Our plan here is to add a simple "starterkit" to the theme, which users will be able to (a) refer to as an example when looking to create a subtheme, and/or (b) Use it with Radix Drush functionality to generate a subtheme, with a single command. I will be adding a draft PR for this today.

## Issues Found

While working on this issue, I found a few issues, some of which have already been fixed.

- [x] #265 Update the theme's screenshot, fixed by #266.  
- [x] #263 Breadcrumb title template not working with subtheme, fixed by #264.
- [x] [radix] [Task] [Provide a means to rename other additional configuration files](https://www.drupal.org/project/radix/issues/3081166)
- [x] [radix] [Task] [Drush subtheme generator expects the kit to be located in Radix](https://www.drupal.org/project/radix/issues/3081150)

**Comment by shadcn** [comment]
The following are now ready for review:

- [x] [radix] [Task] [Provide a means to rename other additional configuration files](https://www.drupal.org/project/radix/issues/3081166)
- [x] [radix] [Task] [Drush subtheme generator expects the kit to be located in Radix](https://www.drupal.org/project/radix/issues/3081150)

**Comment by shadcn** [comment]
This is not done yet. Waiting on https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/272
